import{a as b,S as w,i as s}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const S="https://pixabay.com/api/",v="53564240-a8c4c5fb04a0c541f79bb8ed2";async function f(o,r){try{return(await b.get(S,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw e}}const h=document.querySelector(".gallery"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div class="info">
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
            </div>
        </li>
        `).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){h.innerHTML=""}const y=document.querySelector(".loader");function p(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const g=document.querySelector(".btn");function P(){g.classList.remove("btn-hidden")}function u(){g.classList.add("btn-hidden")}const L=document.querySelector(".form"),$=L.querySelector('input[name="search-text"]'),B=document.querySelector(".btn");let a=1,d="";L.addEventListener("submit",M);B.addEventListener("click",O);async function M(o){o.preventDefault();const r=$.value.trim();if(!r){s.error({title:"Error",message:"Please enter a search word!"});return}d=r,a=1,E(),u(),p();try{const e=await f(d,a);if(e.hits.length===0){s.error({title:"No results",message:"Sorry,nothing found"}),l();return}m(e.hits),Math.ceil(e.totalHits/15)>1?P():(u(),s.info({title:"END",message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({title:"Error",message:"Something went wrong. Try again later."})}finally{l()}}async function O(){a+=1,p();try{const o=await f(d,a);m(o.hits);const r=Math.ceil(o.totalHits/15);a>=r&&(u(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),x()}catch{s.error({title:"Error",message:"Something went wrong."})}finally{l()}}function x(){const o=document.querySelector(".gallery-item");if(!o)return;const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
